### ISSUE TITLE
Readme has an error in the url to original article comments

### ISSUE THREAD

**Issue by hanspf** [davestewart/nuxt-layers-demo#1]
In the readme file the link is:
http://davestwart.co.uk/blog/nuxt-layers/#hyvor-talk-view

Should be:
http://davestewart.co.uk/blog/nuxt-layers/#hyvor-talk-view

Anyway, thank you so much for the article. Used it as a blueprint when migrating a project.

**Comment by davestewart** [comment]
Thanks for the fix!
